### ISSUE TITLE
Arrow position is ambiguous

### ISSUE THREAD

**Issue by sauravgarg540** [pierpo/react-archer#76] opened 2020-01-07 11:35 UTC
Here is a sandbox link to replicate the issue.
https://codesandbox.io/s/musing-beaver-bzk9y

As I have understood after reading the documentation the placement of the arrows is ambiguous and I think it is a bug. 
On changing the targetId: "element4" again places arrow wrongly.

Thanks

**Comment by pierpo** [comment] 2020-01-07 12:59
Hey, thanks for the issue!

I don't see anything unexpected. It looks bad indeed, but it's not related to `react-archer`.

If you inspect the element using the dev tools, you'll notice that the arrow really goes to the middle of the top part of the element:

<img width="508" alt="Capture d’écran 2020-01-07 à 13 56 51" src="https://user-images.githubusercontent.com/6313316/71897069-be207200-3155-11ea-98df-1924b55e0c79.png">

The problem is in the layout itself: `Element 3` should not occupy the full width of the page.

Please tell me if I misunderstood something 😊 
Thanks!

**Comment by sauravgarg540** [comment] 2020-01-07 13:39
Thank you for the fast reply. One more thing when I am not bale to connect Element3 bottom to Element4 bottom.

![Screenshot from 2020-01-07 14-38-51](https://user-images.githubusercontent.com/17601899/71899198-7dc3f280-315b-11ea-85ef-71a551dce7fa.png)

**Comment by pierpo** [comment] 2020-01-07 19:03
@sauravgarg540 Related to #69 indeed! Unfortunately it requires big changes, so I won't fix this before a while :cry: 

Closing this issue since your original problem was expected behaviour.

**Closed by pierpo** 2020-01-07 19:03 UTC
