### ISSUE TITLE
Does not rerender on arrow's element position change

### ISSUE THREAD

**Issue by mitchellwarr** [pierpo/react-archer#86] opened 2020-04-01 00:50 UTC
If the elements within the container ever change position, the arrows do not seem to change their position to match

**Comment by Eliav2** [comment] 2020-04-01 16:00
+1 
It seems that the element does not update their position unless  the "relation" is changes.

otherwise it will update only on second render.
see example here:
https://wu9zh.csb.app/
i've writed here my default anchoring and its seems that the position is updating only of the relation list is changing(from "left" to "top" or whatever).

i believe that the problem is found [here](https://github.com/pierpo/react-archer/blob/master/src/ArcherElement.js) it line 26: it checks only the relations property and only if the relation changed its updating its position.
this is wrong behavior.

the owner of this repo please fix!

**Comment by Eliav2** [comment] 2020-04-12 18:17
because no one updates this repo and the code is not written well I've decided to create new from scratch.
see here: https://github.com/Eliav2/react-xarrows
react-xarrows will rerender whenever needed - and its just working - I've well tested it under any normal circumstances.

**Comment by pierpo** [comment] 2020-04-12 23:49
Hello!
Thank you for the reproducing example, but I can't manage to understand the problem. What does not re-render exactly? In what scenario?
Thanks :blush:

**Comment by mitchellwarr** [comment] 2020-04-13 00:01
In my example I had a table list of data. A column of text on the left, and graphs on the second column. You could click a row and expand it so that underneath sub data rows would populate giving more context to the graphs.

In order to visually make the sub rows connect to the expanded row, I used react-archer arrows to do a sort of
```
o Row 1
|
|
--- Row 1-1
|
|
--- Row 1-2

o Row 2
```

But when you expand out the sub rows it pushes the table elements down, and when they get pushed down, react archer doesnt register an update

**Comment by pierpo** [comment] 2020-04-13 00:10
Okay, can you tell me how you hide the elements? Do you unmount them? Do you hide them with CSS only?

**Comment by mitchellwarr** [comment] 2020-04-13 00:24
I actually insert a row after row-index-x and then fill it with another table recursion style 😉 
So mount and unmount.

As for tracking position changes of the relation targets: i think its a bit much to expect of this library as that's a hard thing to do, and your typical use case wont benefit from it. However, just adding a resizeObserver to the wrapping container div so that when it resizes the arrows take a cue to recalculate, would definitely cover my use case.

I would've looked into telling the arrows themselves to recalc, but that seemed like too much to make work with the animating heights and positions.

Either way I wouldnt suggest you try tackle this bug as a high priority as I was using this library in an odd way, and Eliav2's example app can be fixed by just running some kind of recalculate callback when the user makes explicit changes

**Comment by pierpo** [comment] 2020-04-20 16:36
Thank you for the relevant comment. I'll close this issue then 😊

**Closed by pierpo** 2020-04-20 16:36 UTC
Labels: bug
