### ISSUE TITLE
Minified bundle used for production causes arrows not to display as pretty curves

### ISSUE THREAD

**Issue by AlisonWonderlandApps** [pierpo/react-archer#24] opened 2018-12-05 00:44 UTC
Minified bundle used for production causes arrows not to display as pretty curves

These arrows look great when in dev mode. But once I build a prod (using npm build) to go to production, the arrows lose their curve and therefore look straight & warped :(

**Comment by pierpo** [comment] 2018-12-05 08:41
Oh, oops.
I'll have a look.

If you want me to go faster, you may provide a minimal example 😊

**Comment by AlisonWonderlandApps** [comment] 2018-12-06 07:40
@pierpo thankyou!! I will get one together

**Comment by zgec** [comment] 2018-12-14 19:17
Experiencing exactly the same issue here...
I am using Next.js 7.0.2 (and its associated build script)

I should mention, the render happens on client not on server. 

I'll have a closer look tomorrow as well... Thank you so much for this utility btw, its really great (other than this bug) :smile:

**Comment by zgec** [comment] 2018-12-15 11:16
I managed to fix this by cloning the repo @ master and building the lib/react-archer.js file on my own (and then including that one to my codebase instead of the package import).

After finding that this works, I decided to prettify & diff the two files (one that comes from npm and the one I built myself):

```
--- old-react-archer.js Sat Dec 15 12:08:38 2018
+++ react-archer.js Sat Dec 15 12:08:34 2018
@@ -1,6 +1,6 @@
 ! function(t, e) {
   "object" == typeof exports && "object" == typeof module ? module.exports = e(require("react")) : "function" == typeof define && define.amd ? define(["react"], e) : "object" == typeof exports ? exports.ReactArcher = e(require("react")) : t.ReactArcher = e(t.React)
-}(window, function(t) {
+}("undefined" != typeof self ? self : this, function(t) {
   return function(t) {
     var e = {};
 
@@ -630,11 +630,12 @@
             r.setState(function(t) {
               return {
                 fromTo: function(t, e, r) {
-                  return v(t.filter(function(t) {
+                  var n = t.filter(function(t) {
                     return !r.find(function(e) {
                       return e.from.id === t.from.id && e.to.id === t.to.id
                     })
-                  })).concat(v(e))
+                  });
+                  return [].concat(v(n), v(e))
                 }(t.fromTo, o, i)
               }
             })
@@ -775,6 +776,9 @@
               }, o.a.createElement("svg", {
                 style: m
               }, o.a.createElement("defs", null, this.generateAllArrowMarkers()), t), o.a.createElement("div", {
+                style: {
+                  height: "100%"
+                },
                 ref: this.storeParent
               }, this.props.children)))
             }
```

So, it seems to me that these are actually changes from recent (merged) commits that fixed this issue but havent been published to npm yet?

**Comment by pierpo** [comment] 2018-12-16 10:19
@zgec Yes indeed! This fix was done in this PR https://github.com/pierpo/react-archer/pull/29, and I did not publish.

Will do right now!

Very nice job at debugging it, thank you very much 😊

**Comment by AlisonWonderlandApps** [comment] 2019-01-09 23:19
Thankyou @pierpo !! I'm really impressed by your dedication to this library and your responsiveness to issues as well! Great job! 👍 🥇

**Comment by pierpo** [comment] 2019-01-10 08:45
@AlisonWonderlandApps Thanks for the kind words 😊
Actually I did not fix this issue myself, @jfo84 did 😉

**Comment by geoff-va** [comment] 2019-01-11 21:58
I am actually still running into this issue - the arrows work fine in dev mode and then once minified with `npm run build`, the anchors aren't on the correct sides. Everything seems to be offset and one arrow is actually pointing in the wrong direction now (back in on itself):

**Production**
![production](https://user-images.githubusercontent.com/11033703/51061594-a77a2600-15a8-11e9-828f-30b0de96de2d.png)

**Dev**
![dev](https://user-images.githubusercontent.com/11033703/51061601-aba64380-15a8-11e9-91e6-21820b7c1e33.png)

Highlighted box on the left is the target object.

Thanks!

**Comment by jfo84** [comment] 2019-01-14 11:19
Hey @geoff-va, I can take a look at this but I don't have any immediate guesses. Seems very odd at first glance

**Comment by jfo84** [comment] 2019-01-16 15:02
We generate different `path` elements in prod vs. dev. I haven't been able to reproduce with our example-generating code, but here are two SVGs from an internal build

Dev

`<path d="M129.515625,120 C129.515625,0 129.515625,254.375 129.515625,254.375" marker-end="url(http://localhost:3000/builder/5beede0ab36ff0000c5cf7cf#arrow4311765736827995038b1fcc1c624c569fdf206eb351a20bbcbdd4bfae584e0394dafbb6009365aa)" style="fill: none; stroke: black; stroke-width: 2;"></path>`

Prod

`<path d="M129.515625,120 C129.515625,177.1875 129.515625,177.1875 129.515625,234.375" marker-end="url(http://localhost:3000/builder/5beede0ab36ff0000c5cf7cf#arrow9857085928374139038b1fcc1c624c569fdf206eb351a20bbcbdd4bfae584e0394dafbb6009365aa)" style="fill: none; stroke: black; stroke-width: 2;"></path>`

The cubic bezier section "C" of the path has identical X coordinates but the Y coordinates are wrong

**Comment by jfo84** [comment] 2019-01-18 14:43
Long story short @geoff-va, I believe that this is an evil Terser function inlining bug. The code in SvgArrow was getting optimized to pass 0 to most of the arguments in `computeStartingAnchorPosition`. This is easily the craziest bug I've ever encountered.

Issue in Terser:
https://github.com/terser-js/terser/issues/244

**Comment by geoff-va** [comment] 2019-01-18 17:12
@jfo84 - Amazing detective work man! This does sound like what I was seeing. I remember seeing C0 instead of like C600 for some of the curve descriptions. I really appreciate you digging into this man! Kudos to you!

**Comment by AlisonWonderlandApps** [comment] 2019-01-27 00:14
@jfo84 I'm using create-react-app, and packaging with docker.  I continue to have this issue in prod... not sure how I would go about implementing a workaround here

**Comment by jfo84** [comment] 2019-01-27 08:12
@AlisonWonderlandApps Are you on v1.0.2? If that doesn't fix it, then you'll have to eject your Webpack config and manually apply the minimizer change above

**Comment by AlisonWonderlandApps** [comment] 2019-03-06 07:04
For anyone interested, I used [react-app-rewired](https://github.com/timarney/react-app-rewired) to override this problem without ejecting my app: 
`npm install react-app-rewired --save-dev`
Then in package.json file change the scripts object to:
`  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject"
  },`
Then create a config.overrides.js file in root directory and put the following in it:
`/* config-overrides.js */
// THIS FILE FIXES THE PRODUCTION ISSUE OF react-archer arrow library.
// PLEASE ALSO LEAVE THE PACKAGE.JSON FILE that referenes rewired in the build script

const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const safePostCssParser = require('postcss-safe-parser');
 
module.exports = function override(config, env) {
  console.log(config.optimization);
  config.optimization.minimizer = [
    new OptimizeCSSAssetsPlugin({
      cssProcessorOptions: {
        parser: safePostCssParser,
        map: {
          // `inline: false` forces the sourcemap to be output into a
          // separate file
          inline: false,
          // `annotation: true` appends the sourceMappingURL to the end of
          // the css file, helping the browser find the sourcemap
          annotation: true,
        },
      },
    }),
  ];
  return config;
};`

**Comment by pierpo** [comment] 2019-05-02 16:37
Thank you so much @jfo84 for investigating successfully this hard problem!
Thank you @AlisonWonderlandApps for proposing a working solution, I'm sure it'll help a lot of people.

Closing this since it's not an issue related to `react-archer`.

**Closed by pierpo** 2019-05-02 16:37 UTC

**Comment by lishine** [comment] 2019-09-06 10:21
Next.js 9
This worked for me:
```
const nextConfig = {
    webpack: (config, { dev }) => {
        config.optimization.minimizer[0].options.terserOptions.compress.inline = false
        return config
    },
}
```

**Comment by gpurgal** [comment] 2020-01-21 14:23
Solution proposed by @AlisonWonderlandApps works  but it completely removes `TerserPlugin`.

@lishine's solution works with react-app-rewired and disables only `inline`compress option in `TerserPlugin`:

```
/* config-overrides.js */
module.exports = function override(config, env) {
  config.optimization.minimizer[0].options.terserOptions.compress.inline = false;
  return config;
};
```
